/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketvzla.Vista;

import javax.swing.JFrame;
import marketvzla.Controlador.LoginController;

/**
 *
 * @author migue
 */
public class LoginVista extends javax.swing.JFrame {

    /**
     * Creates new form LoginVista
     */
    public LoginVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        LblLoginUsuario = new javax.swing.JLabel();
        lblLoginPass = new javax.swing.JLabel();
        textLoginUsuario = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnRecuperarPass = new javax.swing.JButton();
        lblLoginRegistro = new javax.swing.JLabel();
        lblLoginRecuperarPass = new javax.swing.JLabel();
        lblLoginErrorUsuario = new javax.swing.JLabel();
        lblLoginErrorPass = new javax.swing.JLabel();
        jbtnSalir = new javax.swing.JButton();
        textLoginPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblLoginUsuario.setText("Usuario");

        lblLoginPass.setText("Contraseña");

        jbtnLogin.setText("Login");

        jbtnRegistrar.setText("Registrar");

        jbtnRecuperarPass.setText("Recuperar");

        lblLoginRegistro.setForeground(new java.awt.Color(51, 51, 255));
        lblLoginRegistro.setText("¿Nuevo Usuario?");

        lblLoginRecuperarPass.setForeground(new java.awt.Color(51, 51, 255));
        lblLoginRecuperarPass.setText("Recuperar contraseña");

        lblLoginErrorUsuario.setForeground(new java.awt.Color(255, 0, 0));
        lblLoginErrorUsuario.setText("¡Usuario incorrecto!");

        lblLoginErrorPass.setForeground(new java.awt.Color(255, 51, 51));
        lblLoginErrorPass.setText("¡Contraseña incorrecta!");

        jbtnSalir.setText("Salir");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLoginRegistro)
                    .addComponent(lblLoginPass)
                    .addComponent(LblLoginUsuario))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnLogin)
                            .addComponent(textLoginUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(textLoginPassword))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoginErrorUsuario)
                            .addComponent(lblLoginErrorPass))
                        .addGap(197, 197, 197))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnSalir)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(jbtnRegistrar)
                                .addGap(42, 42, 42)
                                .addComponent(jbtnRecuperarPass)))
                        .addGap(18, 18, 18)
                        .addComponent(lblLoginRecuperarPass)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblLoginUsuario)
                    .addComponent(textLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginErrorUsuario))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginPass)
                    .addComponent(lblLoginErrorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnLogin)
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRegistrar)
                    .addComponent(lblLoginRegistro)
                    .addComponent(jbtnRecuperarPass)
                    .addComponent(lblLoginRecuperarPass))
                .addGap(29, 29, 29)
                .addComponent(jbtnSalir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void setLoginController (LoginController controller){
    jbtnLogin.addActionListener(controller);
    jbtnRecuperarPass.addActionListener(controller);
    jbtnRegistrar.addActionListener(controller);
    jbtnSalir.addActionListener(controller);
    textLoginPassword.addActionListener(controller);
    textLoginUsuario.addActionListener(controller);
}

public void MustraLogin (){
                lblLoginErrorUsuario.setVisible(false);
                lblLoginErrorPass.setVisible(false);
                setTitle("Bienvenido");
		setResizable(false);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLocationRelativeTo(null);
		setVisible(true);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LblLoginUsuario;
    public javax.swing.JButton jbtnLogin;
    public javax.swing.JButton jbtnRecuperarPass;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JButton jbtnSalir;
    public javax.swing.JLabel lblLoginErrorPass;
    public javax.swing.JLabel lblLoginErrorUsuario;
    public javax.swing.JLabel lblLoginPass;
    public javax.swing.JLabel lblLoginRecuperarPass;
    public javax.swing.JLabel lblLoginRegistro;
    public javax.swing.JPanel panelLogin;
    public javax.swing.JPasswordField textLoginPassword;
    public javax.swing.JTextField textLoginUsuario;
    // End of variables declaration//GEN-END:variables
}
